### ISSUE TITLE
[BUG] Float object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by michelececcacci** [tdryer/editor#2]
When running with  `python3 -m editor`, it crashes with the error message below. 
Operating system:  POP!_OS 22.04 LTS.
Haven't tested on any other operating systems.
```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/michele/personal/python/curses_p/editor/editor/__main__.py", line 363, in <module>
    curses_main()
  File "/home/michele/personal/python/curses_p/editor/editor/__main__.py", line 359, in curses_main
    gui.main()
  File "/home/michele/personal/python/curses_p/editor/editor/__main__.py", line 318, in main
    self._draw()
  File "/home/michele/personal/python/curses_p/editor/editor/__main__.py", line 90, in _draw
    self._draw_text(0, 0, width, height - 1)
  File "/home/michele/personal/python/curses_p/editor/editor/__main__.py", line 230, in _draw_text
    self._stdscr.move(cursor_y + 0, cursor_x + 0)
TypeError: 'float' object cannot be interpreted as an integer```

**Comment by tdryer** [comment]
This was originally written for Python 2.7. It looks like some changes are required to make it work with Python 3.

**Comment by michelececcacci** [comment]
Ok, no problem! I noticed it after creating the issue.
